# Generated by Django 4.1.5 on 2023-01-12 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0002_alter_friends_image'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.RemoveField(
            model_name='order',
            name='description',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.AddField(
            model_name='order',
            name='friend',
            field=models.ForeignKey(blank=True, default=1, help_text='The Diner owner of the Order', on_delete=django.db.models.deletion.CASCADE, related_name='friend_orders', to='friend.friends', verbose_name='Diner'),
            preserve_default=False,
        ),
    ]
