# Generated by Django 4.1.5 on 2023-01-12 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', help_text='Object name', max_length=256, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', help_text='Object description', verbose_name='Description')),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='The Date and the Time of creation on the object', verbose_name='Creation Date and Time')),
                ('edit_date', models.DateTimeField(auto_now=True, help_text='The Date and the Time of last time the object was edited', verbose_name='Last edit Date and Time')),
                ('creation_user', models.CharField(blank=True, default='', help_text='The User that has created the object', max_length=256, verbose_name='Creation User')),
                ('edit_user', models.CharField(blank=True, default='', help_text='The User edited the object last time', max_length=256, verbose_name='Last edit User')),
                ('trash_state', models.SmallIntegerField(default=0, help_text='Indicates if the object is trashed', verbose_name='Trashed')),
                ('image', models.ImageField(help_text='The picture that is shown for the Friend', max_length=255, upload_to='', verbose_name='Profile Image')),
                ('user', models.OneToOneField(help_text='User of this Friend', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
