# Generated by Django 4.1.5 on 2023-01-12 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='image',
            field=models.ImageField(blank=True, help_text='The picture that is shown for the Friend', max_length=255, upload_to='', verbose_name='Profile Image'),
        ),
    ]
