# Generated by Django 4.1.5 on 2023-01-12 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', help_text='Object name', max_length=256, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', help_text='Object description', verbose_name='Description')),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='The Date and the Time of creation on the object', verbose_name='Creation Date and Time')),
                ('edit_date', models.DateTimeField(auto_now=True, help_text='The Date and the Time of last time the object was edited', verbose_name='Last edit Date and Time')),
                ('creation_user', models.CharField(blank=True, default='', help_text='The User that has created the object', max_length=256, verbose_name='Creation User')),
                ('edit_user', models.CharField(blank=True, default='', help_text='The User edited the object last time', max_length=256, verbose_name='Last edit User')),
                ('trash_state', models.SmallIntegerField(default=0, help_text='Indicates if the object is trashed', verbose_name='Trashed')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MenuEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', help_text='Object name', max_length=256, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', help_text='Object description', verbose_name='Description')),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='The Date and the Time of creation on the object', verbose_name='Creation Date and Time')),
                ('edit_date', models.DateTimeField(auto_now=True, help_text='The Date and the Time of last time the object was edited', verbose_name='Last edit Date and Time')),
                ('creation_user', models.CharField(blank=True, default='', help_text='The User that has created the object', max_length=256, verbose_name='Creation User')),
                ('edit_user', models.CharField(blank=True, default='', help_text='The User edited the object last time', max_length=256, verbose_name='Last edit User')),
                ('trash_state', models.SmallIntegerField(default=0, help_text='Indicates if the object is trashed', verbose_name='Trashed')),
                ('image', models.ImageField(help_text='The picture of the current dish', max_length=255, upload_to='', verbose_name='Dish Image')),
                ('max', models.SmallIntegerField(default=0, help_text='Max quantity of portions it is possible to order', verbose_name='Max')),
                ('restaurant', models.ForeignKey(help_text='The Restaurant owner of this Menu Entry', on_delete=django.db.models.deletion.CASCADE, related_name='menu_entries', to='restaurant.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
