# Generated by Django 4.1.5 on 2023-01-12 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuentry',
            name='order_index',
            field=models.SmallIntegerField(default=10, help_text='Used for object ordering', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='menuentry',
            name='image',
            field=models.ImageField(blank=True, help_text='The picture of the current dish', max_length=255, upload_to='', verbose_name='Dish Image'),
        ),
    ]
