# Generated by Django 4.1.5 on 2023-01-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menuentry_order_index_alter_menuentry_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, help_text='The logo picture of the restaurant', max_length=255, upload_to='', verbose_name='Restaurant Logo'),
        ),
    ]
