# Generated by Django 4.1.5 on 2023-01-12 21:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('friend', '0001_initial'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', help_text='Object name', max_length=256, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', help_text='Object description', verbose_name='Description')),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='The Date and the Time of creation on the object', verbose_name='Creation Date and Time')),
                ('edit_date', models.DateTimeField(auto_now=True, help_text='The Date and the Time of last time the object was edited', verbose_name='Last edit Date and Time')),
                ('creation_user', models.CharField(blank=True, default='', help_text='The User that has created the object', max_length=256, verbose_name='Creation User')),
                ('edit_user', models.CharField(blank=True, default='', help_text='The User edited the object last time', max_length=256, verbose_name='Last edit User')),
                ('trash_state', models.SmallIntegerField(default=0, help_text='Indicates if the object is trashed', verbose_name='Trashed')),
                ('reservation_date', models.DateTimeField(default=django.utils.timezone.now, help_text='The Date and Time of the table reservation', verbose_name='reservation Date and Time')),
                ('diners', models.ManyToManyField(help_text='List of diners at the Table', related_name='tables', to='friend.friends', verbose_name='Diners')),
                ('restaurant', models.ForeignKey(help_text='The Restaurant at witch the Table is reserved', on_delete=django.db.models.deletion.CASCADE, related_name='reserved_tables', to='restaurant.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
